global using Microsoft.AspNetCore.Mvc;
global using MTKDotNetCoreAdvancedC_.RepositoryDesignPattern.Persistance.Repositories;
global using Microsoft.EntityFrameworkCore;
global using MTKDotNetCoreAdvancedC_.Database.Models;
global using MTKDotNetCoreAdvancedC_.RepositoryDesignPattern.Handler;