global using Microsoft.AspNetCore.Mvc;
global using MTKDotNetCoreAdvancedC_.RepositoryDesignPattern.Persistance.Repositories;
global using Microsoft.EntityFrameworkCore;
global using MTKDotNetCoreAdvancedC_.Database.Models;
global using MTKDotNetCoreAdvancedC_.RepositoryDesignPattern.Handler;
global using Microsoft.AspNetCore.Diagnostics;
global using MTKDotNetCoreAdvancedC_.Utils;
global using MTKDotNetCoreAdvancedC_.Utils.Enum;
global using MTKDotNetCoreAdvancedC_.RepositoryDesignPattern.Extensions;
